'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BG3_ACHCG.Main", GetType(Main).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_all_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_all.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_meshpath_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_meshpath.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_meshUUID_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_meshUUID.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_snippets_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_snippets.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_texturepath_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_texturepath.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_clear_textureUUID_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_clear_textureUUID.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_gen_allUUID_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_gen_allUUID.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_gen_handle_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_gen_handle.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_gen_meshUUID_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_gen_meshUUID.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_gen_snippets_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_gen_snippets.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_gen_textureUUID_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_gen_textureUUID.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_BM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_BM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_dragon_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_dragon_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_dragon_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_dragon_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_dwarf_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_dwarf_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_dwarf_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_dwarf_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_gith_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_gith_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_gith_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_gith_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_gnome_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_gnome_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_gnome_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_gnome_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_half_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_half_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_half_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_half_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_humanoid_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_humanoid_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_humanoid_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_humanoid_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_humanoid_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_humanoid_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_humanoid_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_humanoid_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_MSK_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_MSK.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_NM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_NM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_orc_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_orc_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_orc_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_orc_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_PM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_PM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_tief_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_tief_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_tief_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_tief_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_tief_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_tief_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property btn_path_tief_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_path_tief_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property cbox_CCAV_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cbox_CCAV.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property cbox_loca_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cbox_loca.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property cbox_merged_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("cbox_merged.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_clear_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_clear.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_generate_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_generate.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_loca_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_loca.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_dragon_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_dragon.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_dwarf_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_dwarf.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_files_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_files.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_gith_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_gith.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_gnome_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_gnome.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_halfling_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_halfling.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_humanoid_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_humanoid.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_orc_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_orc.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_mesh_tiefling_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_mesh_tiefling.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_dragon_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_dragon.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_dwarf_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_dwarf.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_gith_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_gith.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_gnome_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_gnome.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_half_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_half.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_humanoid_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_humanoid.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_orc_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_orc.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_meshUUIDs_tief_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_meshUUIDs_tief.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_snippets_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_snippets.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_textures_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_textures.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_textureUUIDs_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_textureUUIDs.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property grp_UUIDs_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("grp_UUIDs.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_displayed_name_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_displayed_name.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_mesh_prefix_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_mesh_prefix.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_name_handle_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_name_handle.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_BM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_BM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_dragon_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_dragon_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_dragon_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_dragon_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_dwarf_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_dwarf_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_dwarf_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_dwarf_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_gith_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_gith_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_gith_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_gith_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_gnome_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_gnome_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_gnome_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_gnome_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_half_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_half_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_half_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_half_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_humanoid_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_humanoid_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_humanoid_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_humanoid_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_humanoid_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_humanoid_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_humanoid_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_humanoid_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_MSK_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_MSK.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_NM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_NM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_orc_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_orc_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_orc_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_orc_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_PM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_PM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_tief_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_tief_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_tief_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_tief_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_tief_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_tief_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_path_tief_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_path_tief_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_snippet_merged_CCAV_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_snippet_merged_CCAV.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_snippet_merged_loca_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_snippet_merged_loca.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_snippet_merged_material_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_snippet_merged_material.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_snippet_merged_mesh_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_snippet_merged_mesh.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_snippet_merged_textures_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_snippet_merged_textures.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_texture_prefix_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_texture_prefix.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_BM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_BM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_dgb_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_dgb_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_dgb_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_dgb_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_dwr_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_dwr_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_dwr_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_dwr_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_git_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_git_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_git_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_git_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_gnm_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_gnm_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_gnm_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_gnm_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hlf_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hlf_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hlf_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hlf_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hum_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hum_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hum_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hum_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hum_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hum_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_hum_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_hum_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_material_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_material.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_MSK_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_MSK.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_NM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_NM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_orc_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_orc_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_orc_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_orc_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_PM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_PM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_tif_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_tif_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_tif_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_tif_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_tif_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_tif_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property lbl_UUID_tif_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("lbl_UUID_tif_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=125,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property OpenFileDialog_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDialog.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_displayed_name_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_displayed_name.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_mesh_prefix_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_mesh_prefix.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_namehandle_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_namehandle.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_output_CCAV_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_output_CCAV.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_output_loca_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_output_loca.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_output_mergedMaterial_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_output_mergedMaterial.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_output_mergedMesh_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_output_mergedMesh.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_output_mergedTextures_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_output_mergedTextures.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_BM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_BM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_dragon_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_dragon_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_dragon_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_dragon_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_dwarf_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_dwarf_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_dwarf_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_dwarf_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_gith_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_gith_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_gith_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_gith_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_gnome_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_gnome_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_gnome_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_gnome_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_half_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_half_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_half_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_half_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_humanoid_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_humanoid_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_humanoid_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_humanoid_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_humanoid_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_humanoid_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_humanoid_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_humanoid_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_MSK_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_MSK.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_NM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_NM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_orc_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_orc_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_orc_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_orc_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_PM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_PM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_tif_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_tif_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_tif_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_tif_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_tif_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_tif_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_path_tif_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_path_tif_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_texture_prefix_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_texture_prefix.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_BM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_BM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_dgb_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_dgb_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_dgb_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_dgb_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_dwr_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_dwr_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_dwr_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_dwr_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_git_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_git_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_git_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_git_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_gnm_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_gnm_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_gnm_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_gnm_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hlf_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hlf_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hlf_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hlf_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hum_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hum_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hum_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hum_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hum_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hum_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_hum_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_hum_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_material_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_material.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_MSK_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_MSK.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_NM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_NM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_orc_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_orc_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_orc_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_orc_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_PM_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_PM.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_tif_F_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_tif_F.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_tif_FS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_tif_FS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_tif_M_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_tif_M.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property tbox_UUID_tif_MS_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("tbox_UUID_tif_MS.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=260,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property ToolTip_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolTip.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
    End Class
End Namespace
